Repository psy-pri/spotify-analyser, pull requests merged in 2022-10, with the labels that each got.

#2 feat: fix authentication
  main.py
Labels: hacktoberfest, hacktoberfestaccepted

#3 enhancement: automate code generation for auth flow
  .gitignore
  main.py
Labels: enhancement, hacktoberfest, hacktoberfestaccepted, hacktoberfest2022

#4 chore: pylint main.py
  __pycache__/constants.cpython-310.pyc
  main.py
Labels: hacktoberfest, hacktoberfestaccepted, hacktoberfest2022, chore

#5 feat: add DAG definition
  dags/__pycache__/my_dag.cpython-36.pyc
  dags/__pycache__/spotify_dag.cpython-36.pyc
  dags/__pycache__/spotify_etl.cpython-36.pyc
  dags/spotify_dag.py
  dags/spotify_etl.py
Labels: hacktoberfest, hacktoberfestaccepted, hacktoberfest2022
